<script setup>
import { useRoute } from "vue-router";
import { useStore } from "@/stores/store";
import { ref, watch } from "vue";
const route = useRoute();
const store = useStore();

const cities = [
    {
        Version: 1,
        Key: "294021",
        Type: "City",
        Rank: 10,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "",
        Region: {
            ID: "ASI",
            LocalizedName: "Asia",
            EnglishName: "Asia",
        },
        Country: {
            ID: "RU",
            LocalizedName: "Russia",
            EnglishName: "Russia",
        },
        AdministrativeArea: {
            ID: "MOW",
            LocalizedName: "Moscow",
            EnglishName: "Moscow",
            Level: 1,
            LocalizedType: "Federal City",
            EnglishType: "Federal City",
            CountryID: "RU",
        },
        TimeZone: {
            Code: "MSK",
            Name: "Europe/Moscow",
            GmtOffset: 3,
            IsDaylightSaving: false,
            NextOffsetChange: null,
        },
        GeoPosition: {
            Latitude: 55.752,
            Longitude: 37.619,
            Elevation: {
                Metric: {
                    Value: 155,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 508,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Tsentralny",
                EnglishName: "Tsentralny",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
        ],
    },
    {
        Version: 1,
        Key: "332633",
        Type: "City",
        Rank: 65,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "83843",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "ID",
            LocalizedName: "Idaho",
            EnglishName: "Idaho",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "PDT",
            Name: "America/Los_Angeles",
            GmtOffset: -7,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T09:00:00Z",
        },
        GeoPosition: {
            Latitude: 46.732,
            Longitude: -117,
            Elevation: {
                Metric: {
                    Value: 789,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 2587,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Latah",
                EnglishName: "Latah",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "3387968",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "K0K",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "CA",
            LocalizedName: "Canada",
            EnglishName: "Canada",
        },
        AdministrativeArea: {
            ID: "ON",
            LocalizedName: "Ontario",
            EnglishName: "Ontario",
            Level: 1,
            LocalizedType: "Province",
            EnglishType: "Province",
            CountryID: "CA",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/Toronto",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 44.431,
            Longitude: -76.805,
            Elevation: {
                Metric: {
                    Value: 145,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 475,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Lennox And Addington",
                EnglishName: "Lennox And Addington",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2528597",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "KA4 8",
        Region: {
            ID: "EUR",
            LocalizedName: "Europe",
            EnglishName: "Europe",
        },
        Country: {
            ID: "GB",
            LocalizedName: "United Kingdom",
            EnglishName: "United Kingdom",
        },
        AdministrativeArea: {
            ID: "EAY",
            LocalizedName: "East Ayrshire",
            EnglishName: "East Ayrshire",
            Level: 1,
            LocalizedType: "Unitary Authority",
            EnglishType: "Unitary Authority",
            CountryID: "GB",
        },
        TimeZone: {
            Code: "BST",
            Name: "Europe/London",
            GmtOffset: 1,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-10-27T01:00:00Z",
        },
        GeoPosition: {
            Latitude: 55.634,
            Longitude: -4.404,
            Elevation: {
                Metric: {
                    Value: 151,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 495,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 0,
                LocalizedName: "Scotland",
                EnglishName: "Scotland",
            },
            {
                Level: 3,
                LocalizedName: "Irvine Valley",
                EnglishName: "Irvine Valley",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2137023",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "67952",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "KS",
            LocalizedName: "Kansas",
            EnglishName: "Kansas",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 37.324,
            Longitude: -101.206,
            Elevation: {
                Metric: {
                    Value: 936,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 3070,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Stevens",
                EnglishName: "Stevens",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2089993",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "21521",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "MD",
            LocalizedName: "Maryland",
            EnglishName: "Maryland",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 39.544,
            Longitude: -79.005,
            Elevation: {
                Metric: {
                    Value: 525,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 1722,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Allegany",
                EnglishName: "Allegany",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2213039",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "45153",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "OH",
            LocalizedName: "Ohio",
            EnglishName: "Ohio",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 38.857,
            Longitude: -84.229,
            Elevation: {
                Metric: {
                    Value: 139,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 455,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Clermont",
                EnglishName: "Clermont",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "340452",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "18444",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "PA",
            LocalizedName: "Pennsylvania",
            EnglishName: "Pennsylvania",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 41.337,
            Longitude: -75.519,
            Elevation: {
                Metric: {
                    Value: 527,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 1728,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Lackawanna",
                EnglishName: "Lackawanna",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "350829",
        Type: "City",
        Rank: 85,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "38057",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "TN",
            LocalizedName: "Tennessee",
            EnglishName: "Tennessee",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 35.062,
            Longitude: -89.404,
            Elevation: {
                Metric: {
                    Value: 105,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 344,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Fayette",
                EnglishName: "Fayette",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2183385",
        Type: "City",
        Rank: 285,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "04920",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "ME",
            LocalizedName: "Maine",
            EnglishName: "Maine",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 45.121,
            Longitude: -69.872,
            Elevation: {
                Metric: {
                    Value: 388,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 1272,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Somerset",
                EnglishName: "Somerset",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2249744",
        Type: "City",
        Rank: 285,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "53544",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "WI",
            LocalizedName: "Wisconsin",
            EnglishName: "Wisconsin",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 42.864,
            Longitude: -89.897,
            Elevation: {
                Metric: {
                    Value: 300,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 984,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Iowa",
                EnglishName: "Iowa",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2175183",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "22843",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "VA",
            LocalizedName: "Virginia",
            EnglishName: "Virginia",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 38.317,
            Longitude: -79.089,
            Elevation: {
                Metric: {
                    Value: 467,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 1531,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Augusta",
                EnglishName: "Augusta",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2110348",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "75960",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "TX",
            LocalizedName: "Texas",
            EnglishName: "Texas",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 30.913,
            Longitude: -94.825,
            Elevation: {
                Metric: {
                    Value: 99,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 324,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Polk",
                EnglishName: "Polk",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2099028",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "02832",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "RI",
            LocalizedName: "Rhode Island",
            EnglishName: "Rhode Island",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 41.523,
            Longitude: -71.741,
            Elevation: {
                Metric: {
                    Value: 68,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 223,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Washington",
                EnglishName: "Washington",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
            "TidalForecast",
        ],
    },
    {
        Version: 1,
        Key: "2159783",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "39328",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "MS",
            LocalizedName: "Mississippi",
            EnglishName: "Mississippi",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 32.71,
            Longitude: -88.8,
            Elevation: {
                Metric: {
                    Value: 162,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 531,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Kemper",
                EnglishName: "Kemper",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2127157",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "64117",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "MO",
            LocalizedName: "Missouri",
            EnglishName: "Missouri",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 39.166,
            Longitude: -94.542,
            Elevation: {
                Metric: {
                    Value: 250,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 820,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Clay",
                EnglishName: "Clay",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2254142",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "36732",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "AL",
            LocalizedName: "Alabama",
            EnglishName: "Alabama",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 32.438,
            Longitude: -87.996,
            Elevation: {
                Metric: {
                    Value: 21,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 68,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Marengo",
                EnglishName: "Marengo",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2124038",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "46156",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "IN",
            LocalizedName: "Indiana",
            EnglishName: "Indiana",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/Indiana/Indianapolis",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 39.485,
            Longitude: -85.557,
            Elevation: {
                Metric: {
                    Value: 270,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 885,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Rush",
                EnglishName: "Rush",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2083143",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "62926",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "IL",
            LocalizedName: "Illinois",
            EnglishName: "Illinois",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 37.411,
            Longitude: -89.053,
            Elevation: {
                Metric: {
                    Value: 133,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 436,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Union",
                EnglishName: "Union",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2091654",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "71601",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "AR",
            LocalizedName: "Arkansas",
            EnglishName: "Arkansas",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 34.146,
            Longitude: -91.795,
            Elevation: {
                Metric: {
                    Value: 60,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 196,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Jefferson",
                EnglishName: "Jefferson",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2231534",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "35586",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "AL",
            LocalizedName: "Alabama",
            EnglishName: "Alabama",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 33.87,
            Longitude: -88.103,
            Elevation: {
                Metric: {
                    Value: 126,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 413,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Lamar",
                EnglishName: "Lamar",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2184827",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "05672",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "VT",
            LocalizedName: "Vermont",
            EnglishName: "Vermont",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 44.441,
            Longitude: -72.715,
            Elevation: {
                Metric: {
                    Value: 197,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 646,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Lamoille",
                EnglishName: "Lamoille",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2164626",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "42031",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "KY",
            LocalizedName: "Kentucky",
            EnglishName: "Kentucky",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "CDT",
            Name: "America/Chicago",
            GmtOffset: -5,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T07:00:00Z",
        },
        GeoPosition: {
            Latitude: 36.607,
            Longitude: -89.036,
            Elevation: {
                Metric: {
                    Value: 91,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 298,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Hickman",
                EnglishName: "Hickman",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
    {
        Version: 1,
        Key: "2232556",
        Type: "City",
        Rank: 385,
        LocalizedName: "Moscow",
        EnglishName: "Moscow",
        PrimaryPostalCode: "26047",
        Region: {
            ID: "NAM",
            LocalizedName: "North America",
            EnglishName: "North America",
        },
        Country: {
            ID: "US",
            LocalizedName: "United States",
            EnglishName: "United States",
        },
        AdministrativeArea: {
            ID: "WV",
            LocalizedName: "West Virginia",
            EnglishName: "West Virginia",
            Level: 1,
            LocalizedType: "State",
            EnglishType: "State",
            CountryID: "US",
        },
        TimeZone: {
            Code: "EDT",
            Name: "America/New_York",
            GmtOffset: -4,
            IsDaylightSaving: true,
            NextOffsetChange: "2024-11-03T06:00:00Z",
        },
        GeoPosition: {
            Latitude: 40.546,
            Longitude: -80.632,
            Elevation: {
                Metric: {
                    Value: 213,
                    Unit: "m",
                    UnitType: 5,
                },
                Imperial: {
                    Value: 698,
                    Unit: "ft",
                    UnitType: 0,
                },
            },
        },
        IsAlias: false,
        SupplementalAdminAreas: [
            {
                Level: 2,
                LocalizedName: "Hancock",
                EnglishName: "Hancock",
            },
        ],
        DataSets: [
            "AirQualityCurrentConditions",
            "AirQualityForecasts",
            "Alerts",
            "DailyAirQualityForecast",
            "DailyPollenForecast",
            "ForecastConfidence",
            "FutureRadar",
            "MinuteCast",
            "ProximityNotification-Lightning",
            "Radar",
        ],
    },
];
</script>
<template>
    <section class="cities">
        <div class="cities__list">
            <div
                class="cities__item"
                v-for="city in store.cityes"
                :key="city.Key"
            >
                <div class="cities__item-name">
                    {{ city.Country.ID }} {{ city.EnglishName }}
                </div>
                <div class="cities__item-geolocation">
                    {{ city.GeoPosition.Latitude }}
                    {{ city.GeoPosition.Longitude }}
                </div>
                <RouterLink class="btn btn-primary" :to="`/city/${city.Key}`"
                    >More</RouterLink
                >
            </div>
        </div>
        <!-- <pre>{{ cities[0] }}</pre> -->
    </section>
</template>

<style lang="scss" scoped>
.cities {
    &__list {
    }

    &__item {
        padding: 2rem;
        position: relative;
        background: url(../assets/img/bg.jpg) no-repeat center/cover;
    }

    &__item-name {
        font-weight: bold;
    }

    &__item-geolocation {
    }
    btn {
        position: absolute;
        right: 1rem;
        top: 1rem;
    }
}
</style>
